EXTRAKEY_ENABLE   = yes  # Audio control and System control
NKRO_ENABLE       = yes  # N-key rollover
FORCE_NKRO        = yes  # Force N-key rollover
MOUSEKEY_ENABLE   = yes  # Mouse keys
REPEAT_KEY_ENABLE = yes  # Repeat key
OLED_ENABLE       = no   # OLED display
WPM_ENABLE        = no   # WPM
RAW_ENABLE        = no   # Bidirectionnal communication
BOOTMAGIC_ENABLE  = no   # Enable Bootmagic Lite
CONSOLE_ENABLE    = no   # Console for debug
COMMAND_ENABLE    = no   # Commands for debug and configuration
BACKLIGHT_ENABLE  = no   # Enable keyboard backlight functionality
AUDIO_ENABLE      = no   # Audio output
RGBLIGHT_ENABLE   = no   # Enable WS2812 RGB underlight.
SWAP_HANDS_ENABLE = no   # Enable one-hand typing
